#ifndef POSEIDON_HTTP_WEBSOCKET_STATUS_HPP_
#define POSEIDON_HTTP_WEBSOCKET_STATUS_HPP_

namespace Poseidon {

enum WebSocketStatus {
	WS_NORMAL_CLOSURE		= 1000,
	WS_GOING_AWAY			= 1001,
	WS_PROTOCOL_ERROR		= 1002,
	WS_INACCEPTABLE			= 1003,
	WS_RESERVED_UNKNOWN		= 1004,
	WS_RESERVED_NO_STATUS	= 1005,
	WS_RESERVED_ABNORMAL	= 1006,
	WS_INCONSISTENT			= 1007,
	WS_ACCESS_DENIED		= 1008,
	WS_MESSAGE_TOO_BIG		= 1009,
	WS_EXTENSION_NOT_AVAIL	= 1010,
	WS_INTERNAL_ERROR		= 1011,
	WS_RESERVED_TLS			= 1015,
};

const char *getWebSocketStatusDesc(WebSocketStatus status);

}

#endif
